from tkinter import*
root = Tk()
root.geometry("900x700")
root.title("Tic-Tac Games Player")
root.config(bg='#0B074F')
photo = PhotoImage(file="logo.png")
afflogo = Label(root, image=photo)
afflogo.pack()
toptxt = Label(root,text="Tic-Tac the clock is starting!",font=("Arial",40),bg='#0B074F',fg='white')
toptxt.pack()
content = Frame(root)
content.pack()
root.mainloop()
